#!/usr/bin/env bash
#Author: 	Jordan Ulmer
#Date:		2016-12-31
#Purpose: 	git aliases


# Defined in gitconfig
alias gs="git status --short"

alias gco='git checkout'

alias gc='git commit'

alias gd='git diff'

alias gac='git add -A && git commit -m'

alias gb='git branch'

alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"


