#!/usr/bin/env bash
#Author: 	Jordan Ulmer
#Date:		2016-12-31
#Purpose: 	git aliases


# Defined in gitconfig
alias gs="git status --short"

alias gco='git checkout'

alias gc='git commit'

alias gd='git diff'

alias gb='git branch'

alias ga='git add'

alias gr='git reset'

alias gun='git config --local user.name'

alias gue='git config --local user.email'

# alias gfb='git filter-branch --tree-filter 'rm -rf ./projects/a1_uint_multiplier/folder_with_binaries/' --prune-empty HEAD --all'

# alias gac='git add -A && git commit -m'

alias gfp='git fetch --prune'

alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"


