#!/usr/bin/env bash
#Date:      2017-01-04
#Purpose:   Add and remove dirs to global PATH
#Source:    Adapted from Nathan Genetzky - https://github.com/ngenetzky/dotfiles.git

########################################################################

pathadd() {
    pathrm "$1"
    if [ -d "$1" ] && ! echo $PATH | grep -E -q "(^|:)$1($|:)" ; then
        if [ "$2" = "after" ] ; then
            PATH="$PATH:${1%/}"
        else
            PATH="${1%/}:$PATH"
        fi
    fi
}

pathrm() {
    old=$PATH
    PATH="$(echo $PATH | sed -e "s;\(^\|:\)${1%/}\(:\|\$\);\1\2;g" -e 's;^:\|:$;;g' -e 's;::;:;g')"
    if ! [[ $PATH == *"/bin"* ]]
    then
        echo "Don't break the PATH! pathrm-> $PATH"
        PATH=$old
        echo "Reverted to $old"
    fi
}

export -f pathadd
export -f pathrm

########################################################################

# dotfiles
pathadd "$DOTFILES/bin"

# set PATH so it includes user's private bin directories
pathadd "~/bin"
pathadd "~/.local/bin"

# Modelsim
pathadd $HOME/altera/12.1/modelsim_ase/linuxaloem after
pathadd $HOME/altera/16.1/modelsim_ase/linuxaloem after
pathadd $HOME/altera/13.0sp1/modelsim_ase/linuxaloem after

# Quartus
pathadd ~/altera_lite/16.0/quartus/bin after
pathadd ~/altera/13.0sp1/quartus/bin

# GnuWin32
pathrm "/GnuWin32/bin"

# MinGW
pathadd "/c/MinGW/bin/"
