#!/usr/bin/env bash
#Author:    Jordan Ulmer && Nathan Genetzky
#Date:      2017-01-04
#Purpose:   Global system aliases



# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'


# Also derived from source: http://tldp.org/LDP/abs/html/sample-bashrc.html
#-------------------
# Personnal Aliases
#-------------------

# alias rm='rm -i' # This can be annoying
alias cp='cp -avr'
alias mv='mv -i'
# -> Prevents accidentally clobbering files.
alias mkdir='mkdir -p'

alias h='history'
alias j='jobs -l'
alias which='type -a'

# Pretty-print of some PATH variables:
alias path='echo -e ${PATH//:/\\n}'

alias du='du -kh'    # Makes a more readable output.
alias df='df -kTh'

alias reload!='. ~/.bashrc'
alias cls='clear' # Good 'ol Clear Screen command

#-------------------------------------------------------------
# The 'cd' helpers - a quick way to get out of current directory ##
#-------------------------------------------------------------
alias ..='cd ..'
alias .2='cd ../../'
alias ...='cd ../../'
alias .3='cd ../../../'
alias ....='cd ../../../'
alias .4='cd ../../../../'
alias .....='cd ../../../../'
alias .5='cd ../../../../..'

# DIR
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

#-------------------------------------------------------------
# The 'ls' family (this assumes you use a recent GNU ls).
#-------------------------------------------------------------
# Add colors for filetype and  human-readable sizes by default on 'ls':
alias ls='ls -h --color'
alias lx='ls -lXB'         #  Sort by extension.
alias lk='ls -lSr'         #  Sort by size, biggest last.
alias lt='ls -ltr'         #  Sort by date, most recent last.
alias lc='ls -ltcr'        #  Sort by/show change time,most recent last.
alias lu='ls -ltur'        #  Sort by/show access time,most recent last.

# The ubiquitous 'll': directories first, with alphanumeric sorting:
alias l='ls -CF'
#alias ll='ls -alF'
alias ll="ls -lv --group-directories-first"
alias lm='ll |more'        #  Pipe through 'more'
alias lr='ll -R'           #  Recursive ls.
alias la='ll -A'           #  Show hidden files.

# Check tree is installed first.
alias tree='tree -Csuh'    #  Nice alternative to 'recursive ls' ...


### search aliases
if [[ -f $DOTFILES/system/searchaliases ]]; then
    source $DOTFILES/system/searchaliases
fi