#!/usr/bin/env bash
#Author:    Jordan Ulmer
#Date:      2017-01-04
#Purpose:   Install packages
#Source: 
# Constants
APT_PKG_FILE="$(pwd)/packages/apt"
DOTFILES="~/.dotfiles/"

if [[ "$OSTYPE" != "linux"* ]]; then
  echo "$0 : Will only run on Linux"
  exit 1
fi

###############################################################################
# apt-get
###############################################################################

echo "Finding packages to install in: $APT_PKG_FILE"

    if [[ -f $APT_PKG_FILE ]]; then
      exec<$APT_PKG_FILE
      while read line
      do
        if [[ ! "$line" =~ (^#|^$) ]]; then
          packages="$packages $line"
        fi 
      done
    fi
    #return;
    echo "$packages"

echo "apt-git installing $packages"
sudo apt-get install $apt_packages

###############################################################################
# bashrc
###############################################################################
#Purpose:   overwrite sublime user keybindings with .dotfile keybindings

#l(i)n(k) -s(ymbolic) <target> <optional name>
cp -avr ~/.bashrc ~/.bashrc.backup
rm ~/.bashrc
ln -s $DOTFILES/bahsrc/mate.bahsrc ~/.bashrc

###############################################################################
# subl
###############################################################################
#Purpose:   overwrite sublime user keybindings with .dotfile keybindings

cp -avr ~/.config/sublime-text-3/Packages/User/Default\ \(Linux\).sublime-keymap ~/.config/sublime-text-3/Packages/User/Default\ \(Linux\).sublime-keymap.backup
rm ~/.config/sublime-text-3/Packages/User/Default\ \(Linux\).sublime-keymap
ln -s $DOTFILES/subl/Default\ \(Linux\).sublime-keymap.symlink ~/.config/sublime-text-3/Packages/User/Default\ \(Linux\).sublime-keymap
cp -avr ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings.backup
rm ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings 
ln -s $DOTFILES/subl/Preferences.sublime-settings.symlink ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings

