#!/usr/bin/env bash
#Author:    Jordan Ulmer
#Date:      2017-01-04
#Purpose:   Install packages
#Source: 
# Constants
APT_PKG_FILE="$(pwd)/packages/apt"
DOTFILES="~/.dotfiles/"

if [[ "$OSTYPE" != "linux"* ]]; then
  echo "$0 : Will only run on Linux"
  exit 1
fi

###############################################################################
# apt-get
###############################################################################

echo "Finding packages to install in: $APT_PKG_FILE"

    if [[ -f $APT_PKG_FILE ]]; then
      exec<$APT_PKG_FILE
      while read line
      do
        if [[ ! "$line" =~ (^#|^$) ]]; then
          packages="$packages $line"
        fi 
      done
    fi
    #return;
    echo "$packages"

echo "apt-git installing $packages"
sudo apt-get install $apt_packages

###############################################################################
# bashrc
###############################################################################
#Purpose:   overwrite sublime user keybindings with .dotfile keybindings

#l(i)n(k) -s(ymbolic) <target> <optional name>
cp -avr ~/.bashrc ~/.bashrc{,.bak}
rm ~/.bashrc
ln -s $DOTFILES/bahsrc/mate.bahsrc ~/.bashrc

###############################################################################
# subl
###############################################################################
#Purpose:   overwrite sublime user keybindings with .dotfile keybindings

LOCAL_SUBL=~/.config/sublime-text-3/Packages/User/
DOTFILES_SUBL=$DOTFILES/subl/User/

cd LOCAL_SUBL

# TODO: For every file in LOCAL_SUBL, that exists in DOTFILES_SUBL
#       - backup, remove, link
# TODO: Create Function to backup

OLD_FILE=$LOCAL_SUBL/Default\ \(Linux\).sublime-keymap
NEW_FILE=$DOTFILES/Default\ \(Linux\).sublime-keymap
cp -avr $OLD_FILE{,.bak}
rm $OLD_FILE
ln -s $OLD_FILE $NEW_FILE

OLD_FILE=$LOCAL_SUBL/Preferences.sublime-settings
NEW_FILE=$DOTFILES/Preferences.sublime-settings
cp -avr $OLD_FILE{,.bak}
rm $OLD_FILE
ln -s $OLD_FILE $NEW_FILE

OLD_FILE=$LOCAL_SUBL/Package Control.sublime-settings
NEW_FILE=$DOTFILES/Package Control.sublime-settings
cp -avr $OLD_FILE{,.bak}
rm $OLD_FILE
ln -s $OLD_FILE $NEW_FILE
